export interface ToolItem {
  name: string;
  icon: string;
  desc: string;
  url: string;
}

export interface Category {
  title: string;
  items: ToolItem[];
}

export const toolsData: Category[] = [
  {
    title: '前端框架',
    items: [
      {
        name: 'React',
        icon: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicSB.svg',
        desc: '用于构建用户界面的 JavaScript 库',
        url: 'https://react.dev/',
      },
      {
        name: 'Vue',
        icon: 'https://gw.alipayobjects.com/zos/rmsportal/ComBAopevLwENQdKWiIn.png',
        desc: '渐进式 JavaScript 框架',
        url: 'https://vuejs.org/',
      },
      {
        name: 'Angular',
        icon: 'https://gw.alipayobjects.com/zos/rmsportal/zOsKZmFRdUtvpqCImOVY.png',
        desc: '现代 Web 开发平台',
        url: 'https://angular.io/',
      },
      {
        name: 'Svelte',
        icon: 'https://svelte.dev/favicon.png',
        desc: '控制论增强的 Web 应用',
        url: 'https://svelte.dev/',
      },
      {
        name: 'SolidJS',
        icon: 'https://www.solidjs.com/assets/logo-123b04bc.svg',
        desc: '简单高效的响应式 JavaScript 库',
        url: 'https://www.solidjs.com/',
      },
      {
        name: 'Preact',
        icon: 'https://preactjs.com/favicon.ico',
        desc: 'React 的 3kb 轻量化替代方案',
        url: 'https://preactjs.com/',
      },
      {
        name: 'Qwik',
        icon: 'https://qwik.builder.io/logos/qwik-logo.svg',
        desc: '即时加载的 Web 框架',
        url: 'https://qwik.builder.io/',
      },
    ],
  },
  {
    title: '全栈/元框架',
    items: [
      {
        name: 'Next.js',
        icon: 'https://assets.vercel.com/image/upload/v1662130559/nextjs/Icon_light_background.png',
        desc: 'React 应用程序框架',
        url: 'https://nextjs.org/',
      },
      {
        name: 'Nuxt',
        icon: 'https://nuxt.com/icon.png',
        desc: '直观的 Vue 框架',
        url: 'https://nuxt.com/',
      },
      {
        name: 'Remix',
        icon: 'https://remix.run/favicon-32.png',
        desc: '专注于 Web 标准的全栈 Web 框架',
        url: 'https://remix.run/',
      },
      {
        name: 'Astro',
        icon: 'https://astro.build/favicon.svg',
        desc: '构建快速内容驱动网站的一体化 Web 框架',
        url: 'https://astro.build/',
      },
      {
        name: 'SvelteKit',
        icon: 'https://kit.svelte.dev/favicon.png',
        desc: 'Svelte 的官方应用框架',
        url: 'https://kit.svelte.dev/',
      },
    ],
  },
  {
    title: 'UI & CSS',
    items: [
      {
        name: 'Ant Design',
        icon: 'https://gw.alipayobjects.com/zos/rmsportal/KDpgvguMpGfqaHPjicSB.svg',
        desc: '企业级 UI 设计语言和 React 组件库',
        url: 'https://ant.design/',
      },
      {
        name: 'Element Plus',
        icon: 'https://element-plus.org/images/element-plus-logo-small.svg',
        desc: '基于 Vue 3，面向设计师和开发者的组件库',
        url: 'https://element-plus.org/',
      },
      {
        name: 'Tailwind CSS',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg',
        desc: '功能类优先的 CSS 框架',
        url: 'https://tailwindcss.com/',
      },
      {
        name: 'Chakra UI',
        icon: 'https://chakra-ui.com/favicon.png',
        desc: '简单、模块化且易于访问的 React 组件库',
        url: 'https://chakra-ui.com/',
      },
      {
        name: 'Mantine',
        icon: 'https://mantine.dev/favicon.svg',
        desc: '功能齐全的 React 组件库',
        url: 'https://mantine.dev/',
      },
      {
        name: 'shadcn/ui',
        icon: 'https://ui.shadcn.com/favicon.ico',
        desc: '设计精美的可复制粘贴组件',
        url: 'https://ui.shadcn.com/',
      },
      {
        name: 'Styled Components',
        icon: 'https://styled-components.com/favicon.png',
        desc: '组件时代的 CSS',
        url: 'https://styled-components.com/',
      },
      {
        name: 'Sass',
        icon: 'https://sass-lang.com/assets/img/logos/logo.svg',
        desc: '专业级 CSS 扩展语言',
        url: 'https://sass-lang.com/',
      },
      {
        name: 'Emotion',
        icon: 'https://emotion.sh/logo-32x32.png',
        desc: '高效灵活的 CSS-in-JS 库',
        url: 'https://emotion.sh/',
      },
      {
        name: 'Radix UI',
        icon: 'https://www.radix-ui.com/favicon.png',
        desc: '无样式的可访问组件原语',
        url: 'https://www.radix-ui.com/',
      },
    ],
  },
  {
    title: '可视化',
    items: [
      {
        name: 'ECharts',
        icon: 'https://echarts.apache.org/zh/images/favicon.png',
        desc: '一个基于 JavaScript 的开源可视化图表库',
        url: 'https://echarts.apache.org/',
      },
      {
        name: 'D3.js',
        icon: 'https://d3js.org/favicon.png',
        desc: '基于数据操作文档的 JavaScript 库',
        url: 'https://d3js.org/',
      },
      {
        name: 'Chart.js',
        icon: 'https://www.chartjs.org/favicon.ico',
        desc: '简单灵活的 JavaScript 图表',
        url: 'https://www.chartjs.org/',
      },
      {
        name: 'Recharts',
        icon: 'https://recharts.org/favicon.ico',
        desc: '基于 React 和 D3 构建的组合式图表库',
        url: 'https://recharts.org/',
      },
      {
        name: 'Three.js',
        icon: 'https://threejs.org/files/favicon.ico',
        desc: 'JavaScript 3D 库',
        url: 'https://threejs.org/',
      },
      {
        name: 'AntV',
        icon: 'https://gw.alipayobjects.com/zos/rmsportal/PCTJiVmeIcfRhyqmYpay.svg',
        desc: '蚂蚁集团全新一代数据可视化解决方案',
        url: 'https://antv.vision/',
      },
    ],
  },
  {
    title: '开发语言',
    items: [
      {
        name: 'Node.js',
        icon: 'https://nodejs.org/static/images/logo.svg',
        desc: '基于 Chrome V8 引擎的 JavaScript 运行时',
        url: 'https://nodejs.org/',
      },
      {
        name: 'Python',
        icon: 'https://www.python.org/static/favicon.ico',
        desc: '让你工作更高效、集成系统更有效的编程语言',
        url: 'https://www.python.org/',
      },
      {
        name: 'Java',
        icon: 'https://www.oracle.com/asset/web/images/favicon/favicon-32.png',
        desc: '排名第一的编程语言和开发平台',
        url: 'https://dev.java/',
      },
      {
        name: 'Go',
        icon: 'https://go.dev/images/favicon-gopher.png',
        desc: '构建简单、安全、可扩展系统的开源编程语言',
        url: 'https://go.dev/',
      },
      {
        name: 'Rust',
        icon: 'https://www.rust-lang.org/static/images/favicon.svg',
        desc: '一门赋予每个人构建可靠且高效软件能力的语言',
        url: 'https://www.rust-lang.org/',
      },
      {
        name: '.NET',
        icon: 'https://dotnet.microsoft.com/favicon.ico',
        desc: '免费、跨平台、开源的开发者平台',
        url: 'https://dotnet.microsoft.com/',
      },
      {
        name: 'GraalVM',
        icon: 'https://www.graalvm.org/resources/img/logo/graalvm.svg',
        desc: '高性能 JDK 发行版',
        url: 'https://www.graalvm.org/',
      },
    ],
  },
  {
    title: '桌面端框架',
    items: [
      {
        name: 'Electron',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Electron_Software_Framework_Logo.svg',
        desc: '使用 JavaScript，HTML 和 CSS 构建跨平台桌面应用',
        url: 'https://www.electronjs.org/',
      },
      {
        name: 'Tauri',
        icon: 'https://tauri.app/meta/favicon-32x32.png',
        desc: '构建更小、更快、更安全的桌面应用',
        url: 'https://tauri.app/',
      },
      {
        name: 'Flutter',
        icon: 'https://storage.googleapis.com/cms-storage-bucket/54e9f74b444f830ea305.png',
        desc: 'Google 的 UI 工具包，用于通过单一代码库构建精美的应用',
        url: 'https://flutter.dev/',
      },
      {
        name: 'React Native',
        icon: 'https://reactnative.dev/img/favicon.ico',
        desc: '使用 React 构建原生应用',
        url: 'https://reactnative.dev/',
      },
      {
        name: 'Qt',
        icon: 'https://www.qt.io/hubfs/favicon.ico',
        desc: '跨平台软件设计与开发框架',
        url: 'https://www.qt.io/',
      },
      {
        name: '.NET MAUI',
        icon: 'https://dotnet.microsoft.com/favicon.ico',
        desc: '跨平台原生 UI 框架',
        url: 'https://dotnet.microsoft.com/en-us/apps/maui',
      },
      {
        name: 'Wails',
        icon: 'https://wails.io/img/favicon.ico',
        desc: '使用 Go 和 Web 技术构建桌面应用',
        url: 'https://wails.io/',
      },
      {
        name: 'Compose Multiplatform',
        icon: 'https://resources.jetbrains.com/storage/products/compose-multiplatform/img/meta/compose-multiplatform_logo_300x300.png',
        desc: 'JetBrains 推出的声明式 UI 框架',
        url: 'https://www.jetbrains.com/lp/compose-multiplatform/',
      },
    ],
  },

  {
    title: '后端框架',
    items: [
      {
        name: 'Express',
        icon: 'https://expressjs.com/images/favicon.png',
        desc: '简洁灵活的 Node.js Web 框架',
        url: 'https://expressjs.com/',
      },
      {
        name: 'Koa',
        icon: 'https://koajs.com/favicon.png',
        desc: '轻量优雅的 Node.js 框架',
        url: 'https://koajs.com/',
      },
      {
        name: 'NestJS',
        icon: 'https://nestjs.com/favicon.ico',
        desc: '渐进式 Node.js 框架，支持 TypeScript',
        url: 'https://nestjs.com/',
      },
      {
        name: 'Hono',
        icon: 'https://hono.dev/favicon.ico',
        desc: '极速、轻量、Web 标准的 Web 框架',
        url: 'https://hono.dev/',
      },
      {
        name: 'Fastify',
        icon: 'https://fastify.dev/img/favicon.ico',
        desc: '快速低开销的 Web 框架',
        url: 'https://fastify.dev/',
      },
      {
        name: 'Django',
        icon: 'https://www.djangoproject.com/favicon.ico',
        desc: 'Python 高级 Web 框架',
        url: 'https://www.djangoproject.com/',
      },
      {
        name: 'Spring Boot',
        icon: 'https://spring.io/favicon.ico',
        desc: '基于 Spring 的 Java 微服务框架',
        url: 'https://spring.io/projects/spring-boot',
      },
      {
        name: 'FastAPI',
        icon: 'https://fastapi.tiangolo.com/img/favicon.png',
        desc: '快速、现代的 Python API 框架',
        url: 'https://fastapi.tiangolo.com/',
      },
      {
        name: 'Gin',
        icon: 'https://gin-gonic.com/favicon.ico',
        desc: 'Go 语言编写的 HTTP Web 框架',
        url: 'https://gin-gonic.com/',
      },
      {
        name: 'Echo',
        icon: 'https://echo.labstack.com/images/favicon.png',
        desc: '高性能、极简的 Go Web 框架',
        url: 'https://echo.labstack.com/',
      },
      {
        name: 'Actix',
        icon: 'https://actix.rs/favicon.ico',
        desc: 'Rust 强大、实用且极其快速的 Web 框架',
        url: 'https://actix.rs/',
      },
      {
        name: 'Ruby on Rails',
        icon: 'https://rubyonrails.org/assets/images/favicon.png',
        desc: '压缩复杂性的 Web 应用框架',
        url: 'https://rubyonrails.org/',
      },
      {
        name: 'Laravel',
        icon: 'https://laravel.com/img/favicon/favicon-32x32.png',
        desc: 'Web 工匠的 PHP 框架',
        url: 'https://laravel.com/',
      },
    ],
  },
  {
    title: '数据库 & ORM',
    items: [
      {
        name: 'PostgreSQL',
        icon: 'https://www.postgresql.org/favicon.ico',
        desc: '强大的开源关系型数据库',
        url: 'https://www.postgresql.org/',
      },
      {
        name: 'MySQL',
        icon: 'https://www.mysql.com/favicon.ico',
        desc: '最受欢迎的开源关系型数据库',
        url: 'https://www.mysql.com/',
      },
      {
        name: 'MongoDB',
        icon: 'https://www.mongodb.com/favicon.ico',
        desc: '面向文档的 NoSQL 数据库',
        url: 'https://www.mongodb.com/',
      },
      {
        name: 'Redis',
        icon: 'https://redis.io/images/favicon.png',
        desc: '内存键值数据库与缓存',
        url: 'https://redis.io/',
      },
      {
        name: 'SQLite',
        icon: 'https://www.sqlite.org/favicon.ico',
        desc: '小型、快速、自包含的 SQL 数据库引擎',
        url: 'https://www.sqlite.org/',
      },
      {
        name: 'Supabase',
        icon: 'https://supabase.com/favicon/favicon-32x32.png',
        desc: '开源 Firebase 替代方案',
        url: 'https://supabase.com/',
      },
      {
        name: 'Firebase',
        icon: 'https://www.gstatic.com/devrel-devsite/prod/v221007555/firebase/images/favicon.png',
        desc: 'Google 的应用开发平台',
        url: 'https://firebase.google.com/',
      },
      {
        name: 'Prisma',
        icon: 'https://prisma.io/favicon-32x32.png',
        desc: '下一代 TypeScript ORM',
        url: 'https://www.prisma.io/',
      },
      {
        name: 'Drizzle ORM',
        icon: 'https://orm.drizzle.team/favicon.ico',
        desc: 'TypeScript ORM',
        url: 'https://orm.drizzle.team/',
      },
      {
        name: 'TypeORM',
        icon: 'https://typeorm.io/favicon.ico',
        desc: 'TypeScript 和 JavaScript ORM',
        url: 'https://typeorm.io/',
      },
      {
        name: 'Mongoose',
        icon: 'https://mongoosejs.com/docs/images/favicon/favicon-32x32.png',
        desc: 'MongoDB 对象建模工具',
        url: 'https://mongoosejs.com/',
      },
      {
        name: 'Neo4j',
        icon: 'https://neo4j.com/favicon.ico',
        desc: '图形数据库平台',
        url: 'https://neo4j.com/',
      },
    ],
  },
  {
    title: 'AI 开发',
    items: [
      {
        name: 'OpenAI',
        icon: 'https://openai.com/favicon.ico',
        desc: 'AI 模型与 API 平台',
        url: 'https://openai.com/',
      },
      {
        name: 'Anthropic',
        icon: 'https://www.anthropic.com/favicon.ico',
        desc: 'Claude AI 模型开发商',
        url: 'https://www.anthropic.com/',
      },
      {
        name: 'Google Gemini',
        icon: 'https://www.gstatic.com/lamda/images/gemini_favicon_f069958c85030456e93de685481c559f160ea06b.png',
        desc: 'Google 最强大的 AI 模型',
        url: 'https://deepmind.google/technologies/gemini/',
      },
      {
        name: 'Hugging Face',
        icon: 'https://huggingface.co/favicon.ico',
        desc: '模型与数据集社区及工具链',
        url: 'https://huggingface.co/',
      },
      {
        name: 'LangChain',
        icon: 'https://langchain.com/favicon.ico',
        desc: '构建 LLM 应用的工具链',
        url: 'https://langchain.com/',
      },
      {
        name: 'TensorFlow',
        icon: 'https://www.tensorflow.org/favicon.ico',
        desc: '开源机器学习框架',
        url: 'https://www.tensorflow.org/',
      },
      {
        name: 'PyTorch',
        icon: 'https://pytorch.org/assets/images/favicon.png',
        desc: '灵活易用的深度学习框架',
        url: 'https://pytorch.org/',
      },
      {
        name: 'Keras',
        icon: 'https://keras.io/favicon.ico',
        desc: '为人类设计的深度学习 API',
        url: 'https://keras.io/',
      },
      {
        name: 'Scikit-learn',
        icon: 'https://scikit-learn.org/stable/_static/favicon.ico',
        desc: 'Python 机器学习工具',
        url: 'https://scikit-learn.org/',
      },
      {
        name: 'Ollama',
        icon: 'https://ollama.com/public/ollama.png',
        desc: '在本地运行大型语言模型',
        url: 'https://ollama.com/',
      },
      {
        name: 'Midjourney',
        icon: 'https://www.midjourney.com/favicon.ico',
        desc: 'AI 艺术生成工具',
        url: 'https://www.midjourney.com/',
      },
    ],
  },
  {
    title: '区块链开发',
    items: [
      {
        name: 'Solidity',
        icon: 'https://docs.soliditylang.org/en/latest/_static/logo.svg',
        desc: '以太坊智能合约语言',
        url: 'https://soliditylang.org/',
      },
      {
        name: 'Hardhat',
        icon: 'https://hardhat.org/favicon.ico',
        desc: '以太坊开发环境与任务运行器',
        url: 'https://hardhat.org/',
      },
      {
        name: 'Truffle',
        icon: 'https://trufflesuite.com/img/favicon.ico',
        desc: '区块链应用开发框架',
        url: 'https://trufflesuite.com/',
      },
      {
        name: 'Foundry',
        icon: 'https://book.getfoundry.sh/favicon.ico',
        desc: '现代以太坊开发工具套件',
        url: 'https://getfoundry.sh/',
      },
      {
        name: 'Ethers.js',
        icon: 'https://docs.ethers.org/favicon.ico',
        desc: '与以太坊交互的 JavaScript 库',
        url: 'https://docs.ethers.org/',
      },
      {
        name: 'Web3.js',
        icon: 'https://web3js.readthedocs.io/en/v1.7.0/_static/favicon.ico',
        desc: '以太坊 JavaScript API',
        url: 'https://web3js.readthedocs.io/',
      },
      {
        name: 'MetaMask',
        icon: 'https://metamask.io/images/favicon-32x32.png',
        desc: '浏览器加密钱包与 dApp 网关',
        url: 'https://metamask.io/',
      },
      {
        name: 'Solana',
        icon: 'https://solana.com/favicon.ico',
        desc: '高性能区块链平台',
        url: 'https://solana.com/',
      },
      {
        name: 'Polkadot',
        icon: 'https://polkadot.network/favicon.ico',
        desc: '多链互操作性平台',
        url: 'https://polkadot.network/',
      },
      {
        name: 'Chainlink',
        icon: 'https://chain.link/favicon.ico',
        desc: '去中心化预言机网络',
        url: 'https://chain.link/',
      },
      {
        name: 'IPFS',
        icon: 'https://ipfs.tech/favicon.ico',
        desc: '星际文件系统',
        url: 'https://ipfs.tech/',
      },
      {
        name: 'Remix IDE',
        icon: 'https://remix.ethereum.org/favicon.ico',
        desc: '以太坊智能合约在线 IDE',
        url: 'https://remix.ethereum.org/',
      },
    ],
  },
  {
    title: 'API & 工具',
    items: [
      {
        name: 'GraphQL',
        icon: 'https://graphql.org/img/favicon.png',
        desc: 'API 查询语言和运行时',
        url: 'https://graphql.org/',
      },
      {
        name: 'Apollo',
        icon: 'https://www.apollographql.com/favicon.ico',
        desc: 'GraphQL 客户端与服务器生态',
        url: 'https://www.apollographql.com/',
      },
      {
        name: 'gRPC',
        icon: 'https://grpc.io/img/favicon.png',
        desc: '高性能开源 RPC 框架',
        url: 'https://grpc.io/',
      },
      {
        name: 'tRPC',
        icon: 'https://trpc.io/img/logo.svg',
        desc: '端到端类型安全的 API',
        url: 'https://trpc.io/',
      },
      {
        name: 'Postman',
        icon: 'https://www.postman.com/favicon.ico',
        desc: 'API 开发与测试平台',
        url: 'https://www.postman.com/',
      },
      {
        name: 'Insomnia',
        icon: 'https://insomnia.rest/favicon.ico',
        desc: '领先的开源 API 客户端',
        url: 'https://insomnia.rest/',
      },
      {
        name: 'Hoppscotch',
        icon: 'https://hoppscotch.io/favicon.ico',
        desc: '开源 API 开发生态系统',
        url: 'https://hoppscotch.io/',
      },
      {
        name: 'Swagger / OpenAPI',
        icon: 'https://swagger.io/favicon-32x32.png',
        desc: 'API 规范与文档工具',
        url: 'https://swagger.io/',
      },
    ],
  },
  {
    title: '部署 & 云服务',
    items: [
      {
        name: 'Vercel',
        icon: 'https://assets.vercel.com/image/upload/front/favicon/vercel/180x180.png',
        desc: '为前端开发者提供的部署平台',
        url: 'https://vercel.com/',
      },
      {
        name: 'Netlify',
        icon: 'https://www.netlify.com/img/global/favicon/apple-touch-icon.png',
        desc: '静态站点与前端应用部署平台',
        url: 'https://www.netlify.com/',
      },
      {
        name: 'AWS',
        icon: 'https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico',
        desc: '亚马逊云计算服务',
        url: 'https://aws.amazon.com/',
      },
      {
        name: 'Google Cloud',
        icon: 'https://cloud.google.com/images/favicon.ico',
        desc: '谷歌云计算服务',
        url: 'https://cloud.google.com/',
      },
      {
        name: 'Azure',
        icon: 'https://azure.microsoft.com/favicon.ico',
        desc: '微软云计算服务',
        url: 'https://azure.microsoft.com/',
      },
      {
        name: 'Docker',
        icon: 'https://www.docker.com/wp-content/uploads/2022/03/vertical-logo-monochromatic.png',
        desc: '应用容器引擎',
        url: 'https://www.docker.com/',
      },
      {
        name: 'Cloudflare',
        icon: 'https://www.cloudflare.com/img/logo-cloudflare-dark.svg',
        desc: '全球网络云平台',
        url: 'https://www.cloudflare.com/',
      },
      {
        name: 'Heroku',
        icon: 'https://www.heroku.com/favicon.ico',
        desc: '云应用平台',
        url: 'https://www.heroku.com/',
      },
      {
        name: 'DigitalOcean',
        icon: 'https://www.digitalocean.com/favicon.ico',
        desc: '开发者云服务提供商',
        url: 'https://www.digitalocean.com/',
      },
      {
        name: 'Railway',
        icon: 'https://railway.app/favicon.ico',
        desc: '基础设施平台',
        url: 'https://railway.app/',
      },
      {
        name: 'Fly.io',
        icon: 'https://fly.io/static/images/favicon.ico',
        desc: '全球应用分发平台',
        url: 'https://fly.io/',
      },
    ],
  },
  {
    title: '运维 & DevOps',
    items: [
      {
        name: 'Kubernetes',
        icon: 'https://kubernetes.io/images/favicon.png',
        desc: '容器编排平台',
        url: 'https://kubernetes.io/',
      },
      {
        name: 'Terraform',
        icon: 'https://www.terraform.io/favicon.ico',
        desc: '基础设施即代码工具',
        url: 'https://www.terraform.io/',
      },
      {
        name: 'Ansible',
        icon: 'https://www.ansible.com/favicon.ico',
        desc: '自动化配置管理与部署',
        url: 'https://www.ansible.com/',
      },
      {
        name: 'Jenkins',
        icon: 'https://www.jenkins.io/favicon.ico',
        desc: '开源自动化服务器（CI/CD）',
        url: 'https://www.jenkins.io/',
      },
      {
        name: 'GitHub Actions',
        icon: 'https://github.githubassets.com/favicons/favicon.svg',
        desc: 'GitHub 集成的 CI/CD 工作流',
        url: 'https://github.com/features/actions',
      },
      {
        name: 'GitLab CI/CD',
        icon: 'https://gitlab.com/assets/favicon-72a2cad5025aa931d6ea56c3201d1f18e68a8cd39788c7c80d5b2b82aa5143ef.png',
        desc: '持续集成与持续交付',
        url: 'https://docs.gitlab.com/ee/ci/',
      },
      {
        name: 'CircleCI',
        icon: 'https://circleci.com/favicon.ico',
        desc: '持续集成与交付平台',
        url: 'https://circleci.com/',
      },
      {
        name: 'ArgoCD',
        icon: 'https://argo-cd.readthedocs.io/en/stable/assets/favicon.png',
        desc: 'Kubernetes 的声明式 GitOps 持续交付工具',
        url: 'https://argo-cd.readthedocs.io/',
      },
      {
        name: 'Helm',
        icon: 'https://helm.sh/img/favicon-152.png',
        desc: 'Kubernetes 包管理器',
        url: 'https://helm.sh/',
      },
    ],
  },
  {
    title: '监控 & 日志',
    items: [
      {
        name: 'Prometheus',
        icon: 'https://prometheus.io/assets/favicons/favicon.ico',
        desc: '时序数据库与监控报警',
        url: 'https://prometheus.io/',
      },
      {
        name: 'Grafana',
        icon: 'https://grafana.com/static/img/favicons/favicon-32x32.png',
        desc: '可视化与监控仪表盘',
        url: 'https://grafana.com/',
      },
      {
        name: 'Sentry',
        icon: 'https://sentry.io/favicon.ico',
        desc: '应用错误监控平台',
        url: 'https://sentry.io/',
      },
      {
        name: 'Elastic Stack',
        icon: 'https://www.elastic.co/favicon.ico',
        desc: 'Elasticsearch、Logstash、Kibana 日志分析套件',
        url: 'https://www.elastic.co/elastic-stack',
      },
      {
        name: 'Datadog',
        icon: 'https://www.datadoghq.com/favicon.ico',
        desc: '统一监控与安全平台',
        url: 'https://www.datadoghq.com/',
      },
      {
        name: 'New Relic',
        icon: 'https://newrelic.com/favicon.ico',
        desc: '全栈可观测性平台',
        url: 'https://newrelic.com/',
      },
      {
        name: 'Splunk',
        icon: 'https://www.splunk.com/content/dam/splunk2/images/icon/favicon.png',
        desc: '机器数据分析平台',
        url: 'https://www.splunk.com/',
      },
    ],
  },
  {
    title: '构建工具',
    items: [
      {
        name: 'Webpack',
        icon: 'https://webpack.js.org/icon-square-small.85ba630cf0c5f29ae3e3.svg',
        desc: '静态模块打包工具',
        url: 'https://webpack.js.org/',
      },
      {
        name: 'Vite',
        icon: 'https://vitejs.dev/logo.svg',
        desc: '下一代前端开发与构建工具',
        url: 'https://vitejs.dev/',
      },
      {
        name: 'Rollup',
        icon: 'https://rollupjs.org/favicon.png',
        desc: 'JavaScript 模块打包器',
        url: 'https://rollupjs.org/',
      },
      {
        name: 'esbuild',
        icon: 'https://esbuild.github.io/favicon.svg',
        desc: '极速 JavaScript 打包器',
        url: 'https://esbuild.github.io/',
      },
      {
        name: 'Turbopack',
        icon: 'https://turbo.build/images/docs/pack/favicon.ico',
        desc: '针对 Webpack 的增量打包器继承者',
        url: 'https://turbo.build/pack',
      },
      {
        name: 'Parcel',
        icon: 'https://parceljs.org/favicon.ico',
        desc: '零配置构建工具',
        url: 'https://parceljs.org/',
      },
    ],
  },
  {
    title: '测试 & 质量',
    items: [
      {
        name: 'Jest',
        icon: 'https://jestjs.io/img/favicon/favicon.ico',
        desc: 'JavaScript 单元测试框架',
        url: 'https://jestjs.io/',
      },
      {
        name: 'Vitest',
        icon: 'https://vitest.dev/favicon.svg',
        desc: '由 Vite 驱动的极速单测工具',
        url: 'https://vitest.dev/',
      },
      {
        name: 'Cypress',
        icon: 'https://www.cypress.io/favicon.ico',
        desc: '前端端到端测试框架',
        url: 'https://www.cypress.io/',
      },
      {
        name: 'Playwright',
        icon: 'https://playwright.dev/favicon.ico',
        desc: '可靠的端到端测试框架',
        url: 'https://playwright.dev/',
      },
      {
        name: 'Selenium',
        icon: 'https://www.selenium.dev/favicon.ico',
        desc: '浏览器自动化工具',
        url: 'https://www.selenium.dev/',
      },
      {
        name: 'Puppeteer',
        icon: 'https://pptr.dev/favicons/favicon.ico',
        desc: '无头 Chrome Node.js API',
        url: 'https://pptr.dev/',
      },
      {
        name: 'Testing Library',
        icon: 'https://testing-library.com/img/octopus-32x32.png',
        desc: '简单完整的测试实用工具',
        url: 'https://testing-library.com/',
      },
      {
        name: 'ESLint',
        icon: 'https://eslint.org/favicon.ico',
        desc: '可插拔的 JavaScript 代码检查工具',
        url: 'https://eslint.org/',
      },
      {
        name: 'Prettier',
        icon: 'https://prettier.io/favicon.ico',
        desc: '有主见的代码格式化器',
        url: 'https://prettier.io/',
      },
    ],
  },
  {
    title: '包管理 & Monorepo',
    items: [
      {
        name: 'npm',
        icon: 'https://www.npmjs.com/static/images/touch-icons/favicon-32x32.png',
        desc: 'JavaScript 包管理器',
        url: 'https://www.npmjs.com/',
      },
      {
        name: 'Yarn',
        icon: 'https://yarnpkg.com/favicon-32x32.png',
        desc: '快速、可靠的包管理器',
        url: 'https://yarnpkg.com/',
      },
      {
        name: 'pnpm',
        icon: 'https://pnpm.io/favicon.png',
        desc: '快速节省磁盘空间的包管理器',
        url: 'https://pnpm.io/',
      },
      {
        name: 'Nx',
        icon: 'https://nx.dev/favicon.ico',
        desc: '智能、高效的 Monorepo 工具集',
        url: 'https://nx.dev/',
      },
      {
        name: 'Turborepo',
        icon: 'https://turbo.build/favicon.ico',
        desc: '高性能 JavaScript Monorepo 构建系统',
        url: 'https://turbo.build/repo',
      },
      {
        name: 'Lerna',
        icon: 'https://lerna.js.org/images/favicon.ico',
        desc: '管理多包存储库的工具',
        url: 'https://lerna.js.org/',
      },
    ],
  },
  {
    title: '开发工具',
    items: [
      {
        name: 'VS Code',
        icon: 'https://code.visualstudio.com/favicon.ico',
        desc: '重新定义代码编辑',
        url: 'https://code.visualstudio.com/',
      },
      {
        name: 'WebStorm',
        icon: 'https://resources.jetbrains.com/storage/products/webstorm/img/meta/webstorm_logo_300x300.png',
        desc: '最智能的 JavaScript IDE',
        url: 'https://www.jetbrains.com/webstorm/',
      },
      {
        name: 'IntelliJ IDEA',
        icon: 'https://resources.jetbrains.com/storage/products/intellij-idea/img/meta/intellij-idea_logo_300x300.png',
        desc: '领先的 Java 和 Kotlin IDE',
        url: 'https://www.jetbrains.com/idea/',
      },
      {
        name: 'Cursor',
        icon: 'https://cursor.sh/favicon.ico',
        desc: 'AI 优先的代码编辑器',
        url: 'https://cursor.sh/',
      },
      {
        name: 'Warp',
        icon: 'https://www.warp.dev/favicon.ico',
        desc: '21 世纪的终端',
        url: 'https://www.warp.dev/',
      },
      {
        name: 'Neovim',
        icon: 'https://neovim.io/favicon.ico',
        desc: '基于 Vim 的高可扩展文本编辑器',
        url: 'https://neovim.io/',
      },
      {
        name: 'Git',
        icon: 'https://git-scm.com/favicon.ico',
        desc: '分布式版本控制系统',
        url: 'https://git-scm.com/',
      },
      {
        name: 'Oh My Zsh',
        icon: 'https://ohmyz.sh/favicon.ico',
        desc: '管理 Zsh 配置的框架',
        url: 'https://ohmyz.sh/',
      },
      {
        name: 'Fiddler',
        icon: 'https://www.telerik.com/favicon.ico',
        desc: 'Web 调试代理工具',
        url: 'https://www.telerik.com/fiddler',
      },
      {
        name: 'Charles',
        icon: 'https://www.charlesproxy.com/favicon.ico',
        desc: 'HTTP 代理/HTTP 监视器/反向代理',
        url: 'https://www.charlesproxy.com/',
      },
    ],
  },
  {
    title: '常用文档',
    items: [
      {
        name: 'MDN',
        icon: 'https://developer.mozilla.org/favicon-48x48.cbbd161b.png',
        desc: 'Web 文档资源',
        url: 'https://developer.mozilla.org/',
      },
      {
        name: 'TypeScript',
        icon: 'https://www.typescriptlang.org/icons/icon-48x48.png?v=8944a05a8b601855de116c8a56d3b3ae',
        desc: 'JavaScript 的超集',
        url: 'https://www.typescriptlang.org/',
      },
      {
        name: 'Stack Overflow',
        icon: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico',
        desc: '开发者问答社区',
        url: 'https://stackoverflow.com/',
      },
      {
        name: 'DevDocs',
        icon: 'https://devdocs.io/favicon.ico',
        desc: '快速、离线、免费的开发者文档浏览器',
        url: 'https://devdocs.io/',
      },
      {
        name: 'Can I Use',
        icon: 'https://caniuse.com/img/favicon-128.png',
        desc: '浏览器支持查询表',
        url: 'https://caniuse.com/',
      },
      {
        name: 'W3Schools',
        icon: 'https://www.w3schools.com/favicon.ico',
        desc: 'Web 开发学习教程',
        url: 'https://www.w3schools.com/',
      },
    ],
  },
];
